[window]
decorations = "None"
startup_mode = "Maximized"
option_as_alt = "Both"

[font]
size = 20
# size = 15

# normal = { family = "UbuntuSansMono Nerd Font Mono", style = "Regular" }
# bold = { family = "UbuntuSansMono Nerd Font Mono", style = "Bold" }
# italic = { family = "UbuntuSansMono Nerd Font Mono", style = "Italic" }
# bold_italic = { family = "UbuntuSansMono Nerd Font Mono", style = "Bold Italic" }

normal = { family = "IosevkaTerm Nerd Font Mono", style = "Regular" }
bold = { family = "IosevkaTerm Nerd Font Mono", style = "Bold" }
italic = { family = "IosevkaTerm Nerd Font Mono", style = "Italic" }
bold_italic = { family = "IosevkaTerm Nerd Font Mono", style = "Bold Italic" }


[mouse]
hide_when_typing = true

# Mac Tmux keymap support
[keyboard]
bindings = [
  { key = "E", mods = "Command", chars = "\u001be" },
  { key = "V", mods = "Command", chars = "\u001bv" },
  { key = "S", mods = "Command", chars = "\u001bs" },
  { key = "L", mods = "Command", chars = "\u001bl" },
  { key = "H", mods = "Command", chars = "\u001bh" },
  { key = "T", mods = "Command", chars = "\u001bt" },
  { key = "P", mods = "Command", chars = "\u001bp" },
  { key = "N", mods = "Command", chars = "\u001bn" },
  { key = "[", mods = "Command", chars = "\u001b[" },
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "1", mods = "Command", chars = "\u001b1" },
  { key = "2", mods = "Command", chars = "\u001b2" },
  { key = "3", mods = "Command", chars = "\u001b3" },
  { key = "4", mods = "Command", chars = "\u001b4" },
  { key = "5", mods = "Command", chars = "\u001b5" },
  { key = "6", mods = "Command", chars = "\u001b6" },
]
