# set tmux to support 256-color(note that outside of tmux, $TERM must be set to xterm-256color)
set -g default-terminal "screen-256color"
set-option -ga terminal-overrides ",*256col*:Tc"
set -as terminal-overrides ',screen-256color:Ms=\E]52;%p1%s;%p2%s\007'

# set tmux prefix key to ctrl-space
unbind C-b
set -g prefix c-space
# enable OSC 52(copy-paste)
set -g set-clipboard on

# bind -n: 表示直接绑定一个快捷键（无需前缀键 Ctrl-b）。
# bind -r：表示该按键绑定的命令在按住不放时可以重复执行。

# create a new window
bind -n M-n new-window

# close current window
bind -n M-w kill-window

# use Alt-0,1,...,9 to navigation
unbind n
unbind p
unbind 1
unbind 2
unbind 3
unbind 4
unbind 5
unbind 6
unbind 7
unbind 8
unbind 9
unbind 0
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

# switch windows
bind -n M-p previous-window
bind -n M-o next-window

# switch panes
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# resize pane
bind -n M-J resize-pane -D 5
bind -n M-K resize-pane -U 5
bind -n M-L resize-pane -R 5
bind -n M-H resize-pane -L 5

# maximize/minimize current pane
bind -n M-m resize-pane -Z

# pane split
bind -n M-s split-window -v -c "#{pane_current_path}"
bind -n M-v split-window -h -c "#{pane_current_path}"

# enable mouse and vi mode
set -g mouse on
set -g mode-keys vi

# set the window and pane index start at 1
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# press cmd+[ to enter copy-mode; q to quit
bind -n M-[ copy-mode
set-option -g set-clipboard on
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi Y send-keys -X copy-end-of-line
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"
bind -T copy-mode-vi 0 send-keys -X start-of-line
bind -T copy-mode-vi ) send-keys -X end-of-line
# also use prefix+p to paste
bind p paste-buffer
